spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: default2@sandboxd5fd2d630c8f4698959d6c67aab1a3d6.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

echo:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.plcoding.chirp: DEBUG