spring:
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mailgun.org
    username: default2@sandboxd5fd2d630c8f4698959d6c67aab1a3d6.mailgun.org

jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

echo:
  email:
    url: "http://echo.llimapons.com"
  rate-limit:
    ip:
      apply-limit: true